after_success:
    - travis_retry php vendor/bin/coveralls -x build/logs/coverage.xml
    - travis_retry php vendor/bin/test-reporter --coverage-report=build/logs/coverage.xml

before_install:
    - travis_retry composer self-update

branches:
    only:
        - master

cache:
    directories:
        - $HOME/.composer/cache

install:
    - travis_retry composer install --dev --no-interaction --prefer-dist

language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.2

script:
    - mkdir -p build/logs
    - vendor/bin/phpunit
